# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-14 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emara', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='registretion_number',
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='password_confirmation',
            field=models.CharField(default='', max_length=50),
        ),
    ]
