# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-18 13:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Emara', '0003_auto_20171115_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ContactForm',
        ),
        migrations.AlterField(
            model_name='about',
            name='current_section',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='papers',
            name='current_section',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sections',
            name='current_section',
            field=models.IntegerField(),
        ),
    ]
